name: CI Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'app.py'
      - 'model_creation.py'
      - 'result.py'
      - 'lint.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Lint with pylint
        run: |
          python lint.py
